src/routes/map_router.py
from flask import Blueprint, render_template, request, jsonify
from src.controller.database import Database

map_blueprint = Blueprint("map", __name__)


@map_blueprint.route('/', methods=["GET"])
def europe_map():
    countries = Database.find_one('project_data', {'index': 'countries'})['data']
    indicators = Database.find_one('project_data', {'index': 'indicators'})['data']
    return render_template('index.html', countries=countries, indicators=indicators)


@map_blueprint.route("/codes", methods=["POST"])
def get_country_codes():
    country_codes = Database.find_one("project_data", {"index": "country_codes"})
    country_codes['_id'] = str(country_codes['_id'])
    return country_codes

src/routes/nav_router.py
from flask import Blueprint


from src.controller.database import Database

nav_blueprint = Blueprint("nav", __name__)


@nav_blueprint.route("/indicators", methods=["POST"])
def get_countries_indicators():
        ind = Database.find_one("project_data", {"index": "indicators"})
        cn = Database.find_one("project_data", {"index": "countries"})
        ind['_id'] = str(ind['_id'])
        cn['_id'] = str(cn['_id'])

        return {"indicators": ind, "countries": cn}

src/routes/pie_router.py
from flask import Blueprint, render_template
from src.models.pestel_model import Pestel_category_model
from src.controller.database import Database

pie_blueprint = Blueprint("pie", __name__)


@pie_blueprint.route('/', methods=["GET"])
def pestel_pie():
    countries = Database.find_one('project_data', {'index': 'countries'})['data']
    indicators = Database.find_one('project_data', {'index': 'indicators'})['data']
    return render_template("pie_chart.html", countries=countries, indicators=indicators)


@pie_blueprint.route("/indicators", methods=["POST"])
def get_pestel():
    pestel_headers = ['POLITICAL', 'ECONOMICAL', 'SOCIAL', 'TECHNOLOGICAL', 'ECOLOGICAL', 'LEGISLATIVE']
    pestel_values = []

    for category in pestel_headers:
        google_data = Pestel_category_model(category).construct_google_data()
        pestel_values.append(google_data)
    return {"pestel": pestel_values}

src/routes/plot_router.py
from flask import Blueprint, render_template, request, jsonify
from flask import json
from src.controller.database import Database
from src.models.df_model import DfModel
from src.models.indicator_df import IndicatorDf
from src.models.country_df import CountryDf
countries = Database.find_one('project_data', {'index': 'countries'})['data']

plots_blueprint = Blueprint("plots", __name__)


@plots_blueprint.route("/line", defaults={'table': None}, methods=["GET"])
@plots_blueprint.route("/line/<string:table>", methods=["GET"])
def plot_line_chart(table):
    cols = request.args.get('col')
    indicators = Database.find_one('project_data', {'index': 'indicators'})['data']
    return render_template("plots.html", table=table, countries=countries, indicators=indicators, cols=cols)


@plots_blueprint.route("/chart_update/<string:type>", methods=["POST"])
def chart_update(type):
    indicators = Database.find_one('project_data', {'index': 'indicators'})['data']
    # get the ajax variables, in json form and convert to dictionary
    data = request.form.to_dict()
    # get the vars
    cols = data['cols'].replace('[', '').replace(']', '').replace('"', '')
    table = data['selTbl'].replace(' ', '_')
    col_sel = data['col_sel'].replace(' ', '_')
    last_year = data['lastYear']
    predict_flag = data['flag']
    df_obj = DfModel(table, dates_updated=True)

    my_dict, dates, columns, to_google, df_total_col_length, df_index_length, last_year, remaining_cols \
        = df_obj.update_chart(cols, table, last_year, predict_flag=predict_flag, update_type=type, col_sel=col_sel)

    # return in json format
    return {"data": my_dict, "dates": dates, "columns": columns, "to_google": to_google, "last_year": last_year,
            "df_length": df_total_col_length, 'df_index_length': df_index_length, 'table': table,
            'indicators': indicators, 'remaining_cols': remaining_cols}


# returns the columns of the df name (table), in order to fill the 2nd droplist (columns) in the plot.htm
@plots_blueprint.route("/select", methods=["POST"])
def get_columns():
    data = request.form.to_dict()
    table = data['table'].replace(' ', '_')
    df_obj = DfModel(table)
    df_obj.save_df_full()
    cols = [x for x in df_obj.df.columns if x != 'date']

    return jsonify(cols)


@plots_blueprint.route("/initial", methods=["GET"])
def get_initial():
    indicators = Database.find_one('project_data', {'index': 'indicators'})['data']
    col = request.args.get('col')
    table = request.args.get('tbl')
    table = table.replace(' ', '_').replace("'", '')
    if table in countries:
        # get the full df
        df_obj = CountryDf(table)
        # save to mongodb, in collection dataframes
        df_obj.save_df_full()
        df_columns = df_obj.df.columns.tolist()
        # get and save to mongodb (in collection partial dfs), the partial dfs
        df = df_obj.save_df_partial(col)
        df = df.reset_index(drop=True)
        df = df.sort_values(by=['date'], ascending=False)
        collection_name = 'partial_dfs'
        data, color_list, columns = df_obj.get_line(collection_name, col, reverse=True)
    else:
        # get the df object
        df_obj = IndicatorDf(table)
        # get the df of the df object
        df = df_obj.df
        df_obj.df = df.reset_index(drop=True)
        df_obj.df = df_obj.df.sort_values(by=['date'], ascending=False).set_index('date', drop=False)
        df = df_obj.df
        # save to mongodb
        df_obj.save_df_full()
        df_columns = [x.replace('_', ' ') for x in df.columns]
        collection_name = 'dataframes'
        data, color_list, columns = df_obj.get_line(collection_name, col)

    # get the data for the line plot
    years = [str(x).replace('-01-01', '') for x in df['date']]
    # get the data for the table plot
    to_google = df_obj.get_google_data(df, columns, years)
    years = json.dumps(years)

    return {'data': data, "columns": columns, 'years': years, "header": table, 'to_google': to_google,
            'df_columns': df_columns, "indicators": indicators}

src/templates/About.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% set title = 'About MULTIFOR' %}
    {% set title_class =  'small-header' %}
    {% include "favicon.html" %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,600,700" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/queries.css') }}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>
    <script type="module" src="https://unpkg.com/ionicons@5.0.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule="" src="https://unpkg.com/ionicons@5.0.0/dist/ionicons/ionicons.js"></script>
    <title class="small-title" style="margin-left:12px!important;">{{ title }}</title>
{#    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;1,100&display=swap" rel="stylesheet">#}


</head>
<body>
    <header>
        <!--  nav  -->
        {% include "navBar.html" %}
        <!-- End:nav   -->
    </header>
    <div class="about header">
        <h3 style="margin:30px 60px 0 0;color:#888;">Deriving knowledge from Time-series Analysis & Machine Learning</h3>
    </div>

    <div class="about" style="font-family: 'Lato', sans-serif;">
            <p>The need for professional managers to gain additional knowledge, so that they can lead their company ahead its competition, is as necessary as never before.
            The rush volatility and uncertainty that characterizes the global market, and specifically the manufacturing industry, stresses the need for additional knowledge that Business Intelligence and Analytics (BIA) is capable to provide.
            <p>MULTIFOR, which refers to the Multi-scope Industrial Forecasting Framework and is based on time-series data analytics of BIA, is what Decision-Makers seek in the Risk Management sector. It exploits Data Mining with Machine Learning (Long-Short Term Memory Recurrent Neural Networks - LSTM RNNs) into the BIA sector for businesses advantage and in particular for elevator manufacturing industry.</p>
            <p>It has started at 2020 as a part of a MSc thesis project from Data &amp; Web Science student <a href="http://tsiligkeridis.com/" target="_blank">Odysseas Tsiligkeridis</a> with supervision from <a href="https://oswinds.csd.auth.gr/people/athena-vakali" target="_blank">Prof. Athena Vakali</a> and the support of the PhD Candidate<a href="https://gr.linkedin.com/in/vagia-moustaka-556ba982" target="_blank"> Vaia Moustaka</a>, which had subject “MULTIFOR: A multi-scope industrial forecasting framework based on time-series data analytics” and in general is an application which:</p>
            <ul class="circle">
                <li>
                  introduces the Political-Economic-Social-Technological-Ecological-Legal (PESTEL) analysis on the European continent
                </li>
                <li>
                    provides familiarization with the PESTEL analysis indicators and the countries to which they refer
                </li>
                <li>
                    offers the opportunity to conduct analysis on their statistics, through their time-series inspection and comparison
                </li>
                <li>
                    delivers predictions to these countries, taking into regard each country's overall indicators as a multivariate approach
                </li>
                <li>
                    conducts as well, predictions to individual indicators, taking into regard other countries as a multivariate approach
                </li>
            </ul>
            <p>Currently the data has been extracted from major international websites-databases (e.g. WorldBank.com and Eurostat) for the countries displayed in <a href="{{ url_for('map.europe_map') }}" >Map</a> page. It has implemented, so that can be "plugged"
                to the APIs offered by the aforementioned websites-databases to derive its initial data.
                The PESTEL indicators, which can be explored in the <a href="{{ url_for('pie.pestel_pie') }}" >PESTEL analysis</a> page, for the above countries where selected with regard their influence on each other (Spearman's correlation coefficient) and their
                degree of reflecting a country's macro-environmental status. You can conduct analysis and predictions for each individual country or indicator separately by selecting them from the navigation bar, the above two other pages, or from the panel in
                the <a href="#" >Charts</a> page. We will hopefully add more features and case-studies to broaden the range and the variety of data gained and provided.</p>
            <p>If you have any questions regarding the data gathered, suggestions about making statistics more accurate or simply want to contact us, please send us your <a href="{{ url_for('feedback_page') }}" data-reveal-id="feedbackModal">feedback</a></p>
    </div>

    {% include "footer.html" %}

    <script>
        const countries = {{ countries | tojson }}
        const indicators = {{ indicators | tojson}}
        const lineUrl = "{{ url_for('plots.plot_line_chart' ) }}";
        const navUrl = "{{ url_for('nav.get_countries_indicators' ) }}";
        const pestelUrl = "{{ url_for('pie.get_pestel' ) }}";
    </script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/navBar_scripts.js') }}"></script>

</body>
</html>

src/templates/error_404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/error.css') }}" />
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>
</head>
<body>
<svg width="380px" height="500px" viewBox="0 0 837 1045" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns">
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" sketch:type="MSPage">
        <path d="M353,9 L626.664028,170 L626.664028,487 L353,642 L79.3359724,487 L79.3359724,170 L353,9 Z" id="Polygon-1" stroke="#007FB2" stroke-width="6" sketch:type="MSShapeGroup"></path>
        <path d="M78.5,529 L147,569.186414 L147,648.311216 L78.5,687 L10,648.311216 L10,569.186414 L78.5,529 Z" id="Polygon-2" stroke="#EF4A5B" stroke-width="6" sketch:type="MSShapeGroup"></path>
        <path d="M773,186 L827,217.538705 L827,279.636651 L773,310 L719,279.636651 L719,217.538705 L773,186 Z" id="Polygon-3" stroke="#795D9C" stroke-width="6" sketch:type="MSShapeGroup"></path>
        <path d="M639,529 L773,607.846761 L773,763.091627 L639,839 L505,763.091627 L505,607.846761 L639,529 Z" id="Polygon-4" stroke="#F2773F" stroke-width="6" sketch:type="MSShapeGroup"></path>
        <path d="M281,801 L383,861.025276 L383,979.21169 L281,1037 L179,979.21169 L179,861.025276 L281,801 Z" id="Polygon-5" stroke="#36B455" stroke-width="6" sketch:type="MSShapeGroup"></path>
    </g>
</svg>
<div class="message-box">
  <h1>404</h1>
  <p>Page not found</p>
  <div class="buttons-con">
    <div class="action-link-wrap">
      <a onclick="history.back(-1)" class="link-button link-back-button">Go Back</a>
      <a href="" class="link-button">Go to Home Page</a>
    </div>
  </div>
</div>
<script>
    const homeUrl = "{{ url_for('map.europe_map') }}";
    $('.link-button').attr('href', homeUrl);
</script>
</body>
</html>

src/templates/error_500.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/error.css') }}" />
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>
</head>
<body>
<svg width="380px" height="500px" viewBox="0 0 837 1045" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns">
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" sketch:type="MSPage">
        <path d="M353,9 L626.664028,170 L626.664028,487 L353,642 L79.3359724,487 L79.3359724,170 L353,9 Z" id="Polygon-1" stroke="#007FB2" stroke-width="6" sketch:type="MSShapeGroup"></path>
        <path d="M78.5,529 L147,569.186414 L147,648.311216 L78.5,687 L10,648.311216 L10,569.186414 L78.5,529 Z" id="Polygon-2" stroke="#EF4A5B" stroke-width="6" sketch:type="MSShapeGroup"></path>
        <path d="M773,186 L827,217.538705 L827,279.636651 L773,310 L719,279.636651 L719,217.538705 L773,186 Z" id="Polygon-3" stroke="#795D9C" stroke-width="6" sketch:type="MSShapeGroup"></path>
        <path d="M639,529 L773,607.846761 L773,763.091627 L639,839 L505,763.091627 L505,607.846761 L639,529 Z" id="Polygon-4" stroke="#F2773F" stroke-width="6" sketch:type="MSShapeGroup"></path>
        <path d="M281,801 L383,861.025276 L383,979.21169 L281,1037 L179,979.21169 L179,861.025276 L281,801 Z" id="Polygon-5" stroke="#36B455" stroke-width="6" sketch:type="MSShapeGroup"></path>
    </g>
</svg>
<div class="message-box">
  <h1>500</h1>
  <p>Unexpected Error :(</p>
  <div class="buttons-con">
    <div class="action-link-wrap">
      <a onclick="history.back(-1)" class="link-button link-back-button">Go Back</a>
      <a href="" class="link-button">Go to Home Page</a>
    </div>
  </div>
</div>
<script>
    const homeUrl = "{{ url_for('map.europe_map') }}";
    $('.link-button').attr('href', homeUrl);
</script>
</body>
</html>

src/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% set title = 'Europe' %}
    {% set title_class =  'small-header' %}
    {% include "favicon.html" %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,600,700" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/lobibox.min.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/queries.css') }}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>
<!--    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.1.11.min.js') }}"></script>-->
    <script type="text/javascript" src="{{ url_for('static', filename='js/lobibox.min.js') }}"></script>
    <script type="module" src="https://unpkg.com/ionicons@5.0.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule="" src="https://unpkg.com/ionicons@5.0.0/dist/ionicons/ionicons.js"></script>
    <script src="https://www.amcharts.com/lib/4/core.js"></script>
    <script src="https://www.amcharts.com/lib/4/maps.js"></script>
    <script src="https://www.amcharts.com/lib/4/geodata/worldLow.js"></script>
    <script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/spinner.js') }}"></script>

    <title class="small-title">{{ title }}</title>

</head>
<body>
<header>
    <!--  nav  -->
    {% include "navBar.html" %}
    <!-- End:nav   -->
</header>
<div class="map-container">
    <div id="chartdiv"></div>
</div>

{% include "footer.html" %}

<div class="test"></div>
<script>
    const countries = {{ countries | tojson }}
    const indicators = {{ indicators | tojson}}
    const lineUrl = "{{ url_for('plots.plot_line_chart' ) }}";
    const navUrl = "{{ url_for('nav.get_countries_indicators' ) }}";
    const getMapUrl = "{{ url_for('map.get_country_codes' ) }}";
    const error404Html = "{{ url_for('error_page', code = "404") }}";
    const error500Html = "{{ url_for('error_page', code = "500") }}";
</script>

<script type="text/javascript" src="{{ url_for('static', filename='js/map_script.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/navBar_scripts.js') }}"></script>
</body>
</html>

src/templates/navBar.html
{% block nav %}
    <div class="main-header">
        <img src="{{ url_for('static', filename='img/multifor-logo.png') }}" alt="DWS logo" class="logo left">

        <h1 class="left {{ title_class }}">{{ table }}</h1>
        <div class="right">
        <a class="mobile-nav-icon js--nav-icon"><ion-icon class="icon-menu" name="menu"></ion-icon></a>
        <nav>
            <ul class="main-nav js--main-nav">
                <li><a >Charts</a>
                    <ul >
<!--                            <li><a href="#plans">Greecep</a></li>-->
                        <li class="plots"><a >Countries</a>
                            <ul class="countries-list">
<!--                                    <li><a href="#plans">Greecep</a></li>-->
<!--                                    <li><a href="#plans">Greecep</a></li>-->
                            </ul>
                        </li>
                        <li class="plots"><a >Indicators</a>
                            <ul class="indicators-list">
<!--                                  <li><a href="#plans">Greecep</a></li>-->
<!--                                  <li><a href="#plans">Greecep</a></li>-->
                            </ul>
                        </li>
<!--                           <li><a href="#plans">Greecep</a></li>&ndash;&gt;-->
<!--                            <li><a href="#plans">Greecep</a></li>-->
                    </ul>


                </li>
                <li><a class='btn-map' href="{{ url_for('map.europe_map') }}">Map</a></li>
                <li><a class='btn-pestel-pie' href="{{ url_for('pie.pestel_pie') }}">PESTEL analysis</a></li>

            </ul>
        </nav>
        </div>

    </div>
   {% endblock %}

src/templates/pie_chart.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% set title = 'PESTEL ANALYSIS' %}
    {% set title_class =  'small-header' %}
    {% include "favicon.html" %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,600,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/lobibox.min.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/queries.css') }}" />
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>
<!--    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.1.11.min.js') }}"></script>-->
    <script type="text/javascript" src="{{ url_for('static', filename='js/lobibox.min.js') }}"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/variable-pie.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
<!--    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>-->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="module" src="https://unpkg.com/ionicons@5.0.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule="" src="https://unpkg.com/ionicons@5.0.0/dist/ionicons/ionicons.js"></script>

    <title class="small-title">{{ title }}</title>

</head>
<body>
    <header>
        <!--  nav  -->
        {% include "navBar.html" %}
        {% block nav %}
        {% endblock %}
        <!-- End:nav   -->
    </header>

    <div class="pestel-container">
        <div class="left-col">
            <div class="pestel-indicators first-indicator " id="legislative"></div>
            <div class="pestel-indicators second-indicator " id="ecological"></div>
            <div class="pestel-indicators third-indicator " id="technological"></div>
        </div>
        <div class="pestel-pie">
            <figure class="highcharts-figure">
              <div id="container"></div>
<!--              <p class="highcharts-description">-->
<!--                Variable radius pie charts can be used to visualize a-->
<!--                second dimension in a pie chart. In this chart, the more-->
<!--                densely populated countries are drawn further out, while the-->
<!--                slice width is determined by the size of the country.-->
<!--              </p>-->
            </figure>
        </div>
        <div class="right-col">
            <div class="pestel-indicators first-indicator " id="political"></div>
            <div class="pestel-indicators second-indicator " id="economical"></div>
            <div class="pestel-indicators third-indicator " id="social"></div>
        </div>
    </div>
    {% include "footer.html" %}
    <script>
        const countries = {{ countries | tojson }}
        const indicators = {{ indicators | tojson}}
        const lineUrl = "{{ url_for('plots.plot_line_chart' ) }}";
        const navUrl = "{{ url_for('nav.get_countries_indicators' ) }}";
        const pestelUrl = "{{ url_for('pie.get_pestel' ) }}";
        const error404Html = "{{ url_for('error_page', code = "404") }}";
        const error500Html = "{{ url_for('error_page', code = "500") }}";
    </script>
     <script type="text/javascript" src="{{ url_for('static', filename='js/navBar_scripts.js') }}"></script>
     <script type="text/javascript" src="{{ url_for('static', filename='js/pestel_pie.js') }}"></script>

</body>
</html>

src/templates/plots.html
<!DOCTYPE html>
<html lang="en">
<head>

    {%set table = table | replace("_", " ") %}
    {% include "favicon.html" %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,600,700" rel="stylesheet">
    <link rel="icon" href="../favicon.svg" type="image/svg+xml" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/lobibox.min.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/queries.css') }}" />
    <script type="module" src="https://unpkg.com/ionicons@5.0.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule="" src="https://unpkg.com/ionicons@5.0.0/dist/ionicons/ionicons.js"></script>
<!--    <script src="http://code.jquery.com/jquery-3.1.1.min.js"></script>-->
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/lobibox.min.js') }}"></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/spinner.js') }}"></script>
    <title class="large-title">{{ table }}</title>

</head>
<body>
    <header>
        <!--  nav  -->
        {% include "navBar.html" %}
        <!-- End:nav   -->
    </header>
<div class="chart-page-container">
    <!--  chart-page  -->
    {% include "plots/line_form.html" %}
    <!-- End:chart-page   -->

</div>
{% include "footer.html" %}

    {% set columns=cols %}
    <script>
        // var urls declaration with jinja url methods
        const table = {{ table | tojson }};
        const countries = {{ countries | tojson }};
        const indicators = {{ indicators | tojson}};
        const columns = "{{ columns }}";
        const spinnerIcon = "{{ url_for('static', filename='img/icons.svg') }}";
        const lineUrl = "{{ url_for('plots.plot_line_chart' ) }}";
        const selectUrl = "{{ url_for('plots.get_columns' ) }}";
        const error404Html = "{{ url_for('error_page', code = "404") }}";
        const error500Html = "{{ url_for('error_page', code = "500") }}";
        const remYearUrl = "{{ url_for('plots.chart_update', type='remYear') }}";
        const addYearUrl = "{{ url_for('plots.chart_update', type='addYear') }}";
        const addColUrl = "{{ url_for('plots.chart_update', type='addCol') }}";
        const remColUrl = "{{ url_for('plots.chart_update', type='remCol') }}";
        const switchBtnUrl = "{{ url_for('plots.chart_update', type='switch') }}";
        const updBtnUrl = "{{ url_for('plots.chart_update', type='update') }}";
        const initialUrl = "{{ url_for('plots.get_initial', col=columns) }}";
    </script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/navBar_scripts.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/line_plot.js') }}"></script>
</body>
</html>